name: Environment Access Request
description: To request access to dev tools
title: Access for [individual]
labels: ['external-request', 'operations, ops-access-request']
body:
  - type: markdown
    attributes:
      value: |
        1. Fill out **Description**
        2. Change the **Title** to include your name
        3. Add the label used by your team (eg: `BAH-526`)
        4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
        5. When the issue is closed you will be notified and can continue with on-boarding setup
  - type: input
    id: cor-name
    attributes:
      label: COR Name
      description: Please provide your Contracting Officer's Representative (COR) name.
      placeholder: ex. Janet Doe
    validations:
      required: true
  - type: input
    id: vendor
    attributes:
      label: Vendor Onboarding Representative Name
      description: This is the person from the contracting company responsible for your onboarding process.
      placeholder: ex. Janet Doe
    validations:
      required: true
  - type: input
    id: requestor-name
    attributes:
      label: Your Name
      description: Please provide your name.
      placeholder: ex. Jane Doe
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Your Email
      description: Please provide your name.
      placeholder: jane.doe@gmail.com
    validations:
      required: true
  - type: input
    id: team-name
    attributes:
      label: Name of Your Team
      description: Please provide the name of your team, your role on that team, and the name of the company you work for.
      placeholder: this adds context
    validations:
      required: false
  - type: checkboxes
    id: request-services
    attributes:
      label: Service(s) You Want Access To
      multiple: true
      options:
        - label: SOCKS (Requires public ssh key)
        - label: AWS
  - type: textarea
    id: ssh-key
    attributes:
      label: Public SSH Key
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: 
      render: shell
  - type: textarea
    id: aws-access
    attributes:
      label: Desired AWS Service(s) & Access
      description: What AWS services do you need access to and why? 
      placeholder: I need access to S3 to read uploaded files
